<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sol</string>
	</array>
	<key>name</key>
	<string>Solidity</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>name</key>
			<string>comment.line.solidity</string>
			<key>match</key>
			<string>(?&lt;!tp:)//.*?$</string>  <!-- exclude tp:  at the begining to avoid http:// and ftp:// -->
		</dict>
		<dict>
			<key>name</key>
			<string>comment.block.solidity</string>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Events</string>
			<key>match</key>
			<string>\b(event|enum)\s+([A-Za-z_]\w*)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Main keywords</string>
			<key>match</key>
			<string>\b(contract|struct|function|modifier)\s+([A-Za-z_]\w*)(?:\s+is\s+((?:[A-Za-z_][\,\s]*)*))?\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Built-in types</string>
			<key>match</key>
			<string>\b(address|string\d*|bytes\d*|int\d*|uint\d*|bool|hash\d*)(?:\s+(?:indexed\s+)?([A-Za-z_]\w*)\s*[,\)])?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Mapping definition</string>
			<key>match</key>
			<string>\b(mapping)\s*\((.*)\s+=&gt;\s+(.*)\)(\s+(?:private|public|external|inherited))?\s+([A-Za-z_]\w*)\b</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>True and false keywords</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Langauge keywords</string>
			<key>match</key>
			<string>\b(var|import|function|constant|if|else|for|while|do|break|continue|returns?|private|public|external|inherited|this|suicide|new|is|\_)\b</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Variable definitions</string>
			<key>match</key>
			<string>\b([A-Za-z_]\w+)(\s+(?:private|public|external|inherited))?\s+([A-Za-z_]\w*)\;</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>(=|!|&gt;|&lt;|\||&amp;)</string>
			<key>name</key>
			<string>keyword.control</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>msg and block special usage</string>
			<key>match</key>
			<string>\b(msg|block|tx)\.([A-Za-z_]\w*)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Function call</string>
			<key>match</key>
			<string>\b([A-Za-z_]\w*)\s*\(</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Strings</string>
			<key>match</key>
			<string>([\"\'].*[\"\'])</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>\b(\d+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Hexadecimal</string>
			<key>match</key>
			<string>\b(0[xX][a-fA-F0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comments</string>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\/\*)</string>
			<key>comment</key>
			<string>Multiline comments</string>
			<key>end</key>
			<string>(\*\/)</string>
			<key>name</key>
			<string>comment</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.solidity</string>
	<key>uuid</key>
	<string>ad87d2cd-8575-4afe-984e-9421a3788933</string>
</dict>
</plist>